[pytest]
python_files = test_*.py *_test.py
testpaths = tel/tests/test_bandwidth.py
python_classes = Test*
python_functions = test_*
norecursedirs =
    .*
    build
    dist
    migrations
    feature_2
    feature_3
    old_code
    experiments
addopts = -q
